---
# - name: Add DirectSlave Group
#   group:
#     name: "{{ directslave_group }}"

# - name: Add DirectSlave User
#   user:
#     name: "{{ directslave_user }}"
#     group: "{{ directslave_group }}"
#     shell: /bin/bash
#     home: "{{ directslave_install_dir }}"

- name: Ensure secondary {{ directslave_user }} work directory created
  file:
    path: "{{ directslave_named_secondary_work_dir }}"
    state: directory
    owner: "{{ directslave_user }}"
    group: "{{ directslave_group }}"